baseURL = 'https://chcemtovediet.eu/'
defaultContentLanguage = 'sk'
theme = 'paige'

[languages.sk]
languageCode = 'sk'
languageName = 'Sloven캜ina'
title = 'Chcem To Vedie콘'
weight = 1
contentDir = 'content/sk'

[languages.sk.params.paige.site]
description = 'Informa캜n칳 port치l'

[[languages.sk.menu.main]]
name = 'Domov'
url = '/'
weight = 10

[[languages.sk.menu.main]]
name = 'Inform치cie'
url = '/informacie/'
weight = 20

[[languages.sk.menu.main]]
name = 'Program'
url = '/program/'
weight = 30

[[languages.sk.menu.main]]
name = 'Rozvrh Aktiv칤t'
url = '/rozvrh-aktivit/'
weight = 35

[[languages.sk.menu.main]]
name = 'Uk치쬶a'
url = '/zlomky-od-zakladu/'
weight = 40

[[languages.sk.menu.main]]
name = '游섫릖 English'
url = '/en/'
weight = 100

[languages.en]
languageCode = 'en-us'
languageName = 'English'
title = 'We Want To Know'
weight = 2
contentDir = 'content/en'

[languages.en.params.paige.site]
description = 'Information portal'

[[languages.en.menu.main]]
name = 'Home'
url = '/en/'
weight = 10

[[languages.en.menu.main]]
name = 'Information'
url = '/en/information/'
weight = 20

[[languages.en.menu.main]]
name = 'Program'
url = '/en/program/'
weight = 30

[[languages.en.menu.main]]
name = 'Activity Schedule'
url = '/en/activity-schedule/'
weight = 35

[[languages.en.menu.main]]
name = 'Example'
url = '/en/fractions-from-basics/'
weight = 40

[[languages.en.menu.main]]
name = '游젏릖 Sloven캜ina'
url = '/'
weight = 100

[params.paige.pages]
disable_reading_time = true
disable_toc = true
disable_word_count = true

[params.paige.site]
disable_breadcrumbs = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noclasses = false
style = "github" 