baseURL = 'https://chcemtovediet.eu/'
defaultContentLanguage = 'sk'
theme = 'paige'

[languages.sk]
languageCode = 'sk'
languageName = 'SlovenÄina'
title = 'Chcem To VedieÅ¥'
weight = 1
contentDir = 'content/sk'

[languages.sk.params.paige.site]
description = 'InformaÄnÃ½ portÃ¡l'

[[languages.sk.menu.main]]
name = 'Domov'
url = '/'
weight = 10

[[languages.sk.menu.main]]
name = 'InformÃ¡cie'
url = '/informacie/'
weight = 20

[[languages.sk.menu.main]]
name = 'Program'
url = '/program/'
weight = 30

[[languages.sk.menu.main]]
name = 'ğŸ‡¬ğŸ‡§ English'
url = '/en/'
weight = 100

[languages.en]
languageCode = 'en-us'
languageName = 'English'
title = 'We Want To Know'
weight = 2
contentDir = 'content/en'

[languages.en.params.paige.site]
description = 'Information portal'

[[languages.en.menu.main]]
name = 'Home'
url = '/en/'
weight = 10

[[languages.en.menu.main]]
name = 'Information'
url = '/en/information/'
weight = 20

[[languages.en.menu.main]]
name = 'Program'
url = '/en/program/'
weight = 30

[[languages.en.menu.main]]
name = 'ğŸ‡¸ğŸ‡° SlovenÄina'
url = '/'
weight = 100

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noclasses = false
style = "github" 